### PR TITLE
added dependencies to README

### PR DESCRIPTION
**Pull request by Czechball**
Added Linux dependencies required for running the launcher

### CODE REVIEW

**Comment by TBubba** [comment]
As a Window's guy I'm not too sure what this means, could you please clarify?

**Comment by Czechball** [comment]
These are the Linux dependencies to run the actual Launcher. You need to install them with a package manager (I chose apt) to run the Launcher. Without these, it will just tell you that you are missing them when you try to run the Launcher.

**Comment by Czechball** [comment]
I just noticed the rest of your question, sorry...
They are not distro specific, but are required by Electron.
I'm on Debian Buster 4.19.37-3

**Comment by TBubba** [comment]
Then everything seems to be in order.
Thank you for the PR

**Pull request merged**
