### PR TITLE
Follow XDG standard for config/preferences on Linux

### PR DESCRIPTION
**Pull request by colin969**
The launcher currently reads preferences.json and config.json from the working directory.

Change moves this to the XDG config directory - Electron already stores parts in the flashpoint-launcher folder, so it's set to ~/.config/flashpoint-launcher

Uses a library to check for it, if none is found, falls back to the working directory.

It's all wrapped in a switch based on platform so Windows can be possibly set later on.

### CODE REVIEW

**Comment by TBubba** [comment]
The config and preferences files are located relative to the working directory because that way they are both loaded/saved next to the executable (in release builds) and loaded/saved in the "development folder" while developing.

I know that this can cause issues in some circumstances (like when you try to run the launcher executable from a terminal).

I've planned on

**Comment by TBubba** [comment]
Hello, and thanks for the contribution (and sorry for the closing and reopening, that button is way to easy to click on accident)!

The reason the config and preferences files are located relative to the working directory is that this makes them both load/save next to the executable in release builds and load/save in the "development folder" while developing.

I know that this can cause issues in some circumstances (like when you try to run the launcher executable from a terminal).

I've planned to make the two files load relative to the executable file in release builds, and relative to the working directory while developing.

Could you elaborate what the issue you are trying to solve is?
And would my planned solution cover it?

**Comment by colin969** [comment]
That's the issue - Since configs are required to be next to the exec, it's impossible to have it installed as an application, since it can't write to the install folder.

I've got a pkgbuild that'll build and install from git, along with a proper desktop entry file. Shy of installing to /var/opt and allowing every user write access to the install folder (which at a glance seems like bad practice, might take a second look) there's not much I can do about the config situation.

The Data folder doesn't have this issue since it can (although isn't right now) be located and updated separately from the launcher. Currently I'm building the launcher myself and pointing to the data folder from the experimental download on the wiki.

**Comment by TBubba** [comment]
So if I understand you correctly, your goal is to make the launcher installable on Linux?

We've had discussions about this a long time ago. The guy who's responsible for making the launcher work on Linux (among other things) wanted to make the launcher capable of being both portable and installed. But it got pushed back, and he never got around to implementing it.

Back to the point.

What if the launcher, on startup, checked if there is a file next to the executable named something like ``installed``.
If the file exists, it loads the ``config`` and ``preferences`` files from the config directory.
If not, it loads them the way I described in my previous post.

Would this solution work?

**Comment by colin969** [comment]
That sounds like a good compromise actually. Users shouldn't have multiple
installed versions and wouldn't see the file itself.

Alternatively it could be decided with a build option instead?

**Comment by TBubba** [comment]
Okay, great!

I would prefer that all the builds have the same code, just to keep things simple. But there could be a flag for the build script that create this file automatically.

**Comment by colin969** [comment]
Could you take a look over this? It works but I'd like feedback on the implementation.

I've added 'portable' as a config option in package.json. A possible alternative is creating 11 more script entries in package.json (1 for build, 5 for pack, 5 for release) passing it as an environmental variable.

Replaced xdg-basedir with Electrons cross platform methods. - Looks a lot cleaner now.

**Comment by TBubba** [comment]
I read it and tested it out. It works and it looks like a good starting point.

I think the check for whether or not ``.installed`` exists should be checked from inside ``Main`` and stored as a boolean flag. This has a few benefits:
* It only has to check if the file exists once
* The files existence can be checked asynchronously
* The flag can be passed to other parts of the program too (in case it will be used for other stuff in the future)

The code that creates the ``.installed`` file when "packing" can be moved into the function inside "afterExtract". It would look something like this:
```js
// Create (or don't create) the ".installed" file
if (!config.isPortableInstall) {
  fs.createFileSync(path.join(buildPath, '.installed'));
}
```

I also have some minor notes about coding style. There isn't a properly set up linter or any written guidelines, but there are some things I would like you to keep in mind:
* Use single quotes for strings
* Use semicolons
* Only use ``/** */`` for comments at the top of a file, or right above a declaration (these comments "stick" to that file or declaration). Use ``//`` or ``/* */`` for everything else
* Space out ``if`` and ``for`` statements (ex. ``if (true) {``)

Storing the build options between builds sounds like a nice feature, but I don't think using the package's "config" property is well suited for this. Mainly because it adds the burden of having to make sure you don't accidentally commit changed build options every time you commit. I'm not a big fan of having tons of "scripts", but I think it's better to just add them for now and then look into a better way of providing build options later.

Good job with finding ``app.getPath()`` :+1:

**Comment by colin969** [comment]
Hopefully this is a bit closer to what you're thinking of.

The option is replaced with script entries. Sadly NPM removes white space whenever it updates the file so there can't be a visual separator from the other entries.

Install state is checked in Main and exposed via AppConfigApi. (window.External.config.installed)

Curious behavior to note - Config file is read by main but saved by the renderer, so the file path has to be set in both. Preferences uses an ipc request to main so doesn't have this requirement.

**Comment by TBubba** [comment]
I think this is a good improvement. :+1:

NPM isn't shy about formatting that file. So as longs as the scripts are appropriately named, reasonably well organized and work it's all good in my book.

I very much like the idea of the ``setFilePath`` methods. Especially how it's used for the config file. I think both of them should be called like that, but from inside Main's constructor (preferably right before calling ``Main.loadConfig``). My reasoning is that they should only be called once because the "installed" flag shouldn't be changed during run-time.

I made the renderer process save the config file directly because it was more convenient at the time. But it looks like the tables have turned.

The config and preferences "systems" are almost as old as the launcher, and I don't think they have changed much since their conception. They do serve different purposes (one can be changed during run-time and auto-saves, the other is static) so there are some valid differences between them. But I also think they need a revisit.

I think it would be appropriate to make the main process solely responsible for the config file, and make the renderer process save to it over ipc. This would make the "installed" flag not have to leave the main process (yet). Would you mind if I made this change myself? I'm pretty new to using git collaboratively, so I'm not entirely sure how to properly go about something like that. I'm thinking that I could make a branch (from master) and you could maybe pull it?

Let me know if I missed something or if what I'm saying is incoherent. It's getting pretty late here so I'm not sure how well I'm communicating.

**Comment by colin969** [comment]
I believe there's functionality that lets me give upstream maintainers push
access to the fork it's comparing against so I'll do that in an hour or so
when I can. Hopefully you get a notification or something.

I've done some Collab stuff before but not with pull requests so this is
new to me to

**Comment by colin969** [comment]
Oh, it was already ticked - You should just be able to pull my fork and push right into the configs branch, changes will be reflected here.

When I mean they're kinda oddly named, I mean say, Config has a load method in Main, Preferences has it in PreferencesFile, Config has AppConfig, Preferences has AppPreferencesFile etc. Their method names 

- AppConfig vs AppPreferences**File** - (Both are just read/write file methods)
- read/saveConfigFile vs read/saveFile
- Config defaults in AppConfig, Preferences defaults in shared utils
- Config load function in Main, Preferences load function in AppPreferencesMain (Preferences keeps ipc methods here too, Config just doesn't have any yet)

Was pretty confusing to understand for a while there.

**Pull request merged**
